Mobile-First-Portfolio: Addition of index.html file, style.css file and  linters
AsciencioAlex/mobile-first-portfolio pull request #1
Opened 2023-07-05 23:33 UTC by AsciencioAlex

I did the following in this project
1. Created an index.html file for the mobile portfolio
2. Create a style.css file that styles up the page
3. Added linters folders to the project for removing linters errors

2023-07-05 23:45 UTC, Munsa1 requested changes
Hi @AsciencioAlex, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has missing headers and sections, Kindly note that the only section which can be removed is the `FAQ` section and the `Live Demo` Section if the project has not been deployed and deployment is not a requirement. 

- [ ] Kindly add the `Getting Started`, `Author`, and `Future Features` sections to your ReadMe file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-06 05:05 UTC, Efiamotu-1 requested changes
Hi @AsciencioAlex , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 05:05 UTC, Efiamotu-1 commented on index.html
> +            <span class="__label__list_container"></span></div>
- Your hamburger button should be wrapped around a `nav tag`. The nav tag is for semantics reason, and the right position for convention and user experience for mobile devices. :+1: :sparkles:

2023-07-06 05:05 UTC, Efiamotu-1 commented on index.html
> +            </main>
- [ ]  I think the `main tag` shouldn't be used to wrap the `paragraph`. Please follow this [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) to read me about the `main` tag and how it should be used in sectioning the entire webpage :+1:

2023-07-06 05:05 UTC, Efiamotu-1 commented on index.html
- [ ] As shown in the figma design below you are not posititoning the content of the header properly and the spacing of the content is not the same as the provided figma design as shown by the red lines. Please i kindly suggest that you make the appropriate correction becasue it is important that your design matches completely the provided figma template as this shows how much attention to details you pay as a good frontend developer :+1: :sparkles: 
- figma design
![dis](https://github.com/AsciencioAlex/mobile-first-portfolio/assets/89055502/2c3c244a-fc3a-4cff-8cf3-4d7a5c23dc98)
- your design
![yed](https://github.com/AsciencioAlex/mobile-first-portfolio/assets/89055502/8c008c90-52da-465d-ba6c-79a13f86022c)

2023-07-06 23:26 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @AsciencioAlex 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 23:26 UTC, tresorsawasawa commented on index.html
> +            </div>
- [ ] As mentioned by the previous reviewer and for good semantics reasons, kindly ensure that your Hambarger is wrapped in a `nav` tag i.e. its container tag should be a `<nav>` tag.

2023-07-06 23:26 UTC, tresorsawasawa commented on index.html
> +          <main>
- [ ] As mentioned by the previous reviewer and for best semantics tag, kindly ensure that you use the `main` tag at it s expected place. Below is an example of where to use the `main` tag in a page.
```html
  <header>
    <!-- Header content goes here -->
  </header>

  <main>
    <section>
      <!-- section 1 content goes here -->
    </section>

    <section>
      <!-- section 2 content goes here -->
    </section>

    <section>
      <!-- section 3 content goes here -->
    </section>
    ...
  </main>

  <footer>
    <!-- footer content goes here -->
  </footer>
```

2023-07-06 23:26 UTC, tresorsawasawa commented on index.html
> +              <div class="navbar__logo" href="#"> My Logo</div>
- [ **OPTIONAL** ] **RECOMMENDED:** As this comment was not pointed out by the previous reviewer, kindly ensure that your logo is a link (i.e. it uses a `<a>` tag). This is for three reasons: convention, semantics, and user experience(UX).

2023-07-07 00:03 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED   
 ## Hi  @AsciencioAlex 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Well structured files :white_check_mark:
  * Good Job :+1: :smile: 
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] Check Under the Review

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 00:03 UTC, Alfredbis29 commented on index.html
- [OPTIONAL ] You are not positioning the content of the header appropriately, as shown in the figma design below, and the spacing of the content is not the same as the given figma design. compare your Design to the figma one are not really similar , kindly fix your `background-image` and all it contents  , Kindly fix this :point_down: 
_Even the word Glad to see you_ is not arranged well compare to the design :pray: 

Your Design 
![de](https://github.com/AsciencioAlex/mobile-first-portfolio/assets/88894525/da37e73f-bcba-492f-bfb8-541ec28fed76)

Figma Design 
![Screenshot from 2023-07-07 01-52-20](https://github.com/AsciencioAlex/mobile-first-portfolio/assets/88894525/7933e3df-5067-4f9c-b4b6-bf8b76023095)

2023-07-07 00:05 UTC, merged